environment:
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.9"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4.3"
      PYTHON_ARCH: "32"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "pip install -U pip"
  - "pip install wheel"
  - "mkdir packages"
  - ps: "foreach ($PACKAGE in get-content packages.txt) { pip wheel --no-cache-dir --wheel-dir=.\\packages\\$PACKAGE $PACKAGE }"

artifacts:
  - path: packages\*
